version: '3.6'

services:
  nodejs:
    container_name: tshlx-nodejs
    hostname: tshlx-nodejs
    build:
      dockerfile: nodejs/Dockerfile
    environment:
      - APP_ENV=dev
      - AEM_ADDR=0.0.0.0
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
      - 9229:9229

